singIn update
rnanc/dtm-evaluation pull request #11
Opened 2020-10-14 22:11 UTC by FreitasGa

2020-10-15 12:46 UTC, rnanc requested changes

2020-10-15 12:46 UTC, rnanc commented on templates/details.html
> +			</div>
ta certa essa indentação aqui ?

2020-10-15 12:46 UTC, rnanc commented on templates/measurement.html
> +			</div>
ta certa essa indentação aqui ?

2020-10-15 12:46 UTC, rnanc commented on templates/register_patient.html
> +			</div>
ta certa essa indentação aqui ?

2020-10-15 12:51 UTC, rnanc submitted a review, later dismissed

2020-10-15 12:51 UTC, rnanc commented on static/css/details.css
> +
Trocar por nomes mais descritivos desses elementos

2020-10-15 12:51 UTC, rnanc commented on templates/dashboard.html
>  					<a href="/dashboard" class="active">Pacientes</a>
Este html ta importando seus estilos do details.css, isso precisa ser modularizado, cada pagina precisa de estilos proprios, recomendo criar um dashboard.css e migrar todos os teus estilos para la

2020-10-21 00:50 UTC, olucasfreitas approved these changes
tudo ok

2020-10-21 00:54 UTC, olucasfreitas approved these changes

2020-10-21 19:43 UTC, olucasfreitas approved these changes

2020-10-21 19:44 UTC, olucasfreitas approved these changes

2020-10-21 19:45 UTC, merged